[package]
name = "kube-utils"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
commons = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
moka = { workspace = true, features = ["future"] }
serde_json = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["sync", "fs"] }
